@startuml
left to right direction
' Actores
:Usuario: as Act1
:Administrador: as Act2
:Miembro: as Act3
Act1 <|-- Act2
Act1 <|-- Act3

' Casos de uso
package Categorias as PCKG1{
    package CRUD as PCKG2{
        (Crear) as CU1
        Act1--> CU1
        (Editar) as CU2
        Act1 -->  CU2
        (Buscar) as CU3
        Act1-->  CU3
        CU3 .> CU2 : Include
        (Eliminar) as CU4
        Act1 --> CU4
        CU4 .> CU2 : Include
    }
    package Reportes as PCKG3{
        (Listar Todo)  as CU6
        Act1--> CU6
        (Listar Todo)  as CU7
        CU7--|> CU6
        (por descripcion) as CU8
        CU8 --|> CU6
        (por estado) as CU9
        CU9--|>  CU6
        (por fecha de creacion)  as CU10
        CU10 --|>  CU6
        (por Usuario Creador)  as CU11
        CU11 --|>  CU6
        
    }
}

@enduml
