package FamilyFinances.Views;

import FamilyFinances.Infrastructure.Configurations.DependencyContainer;
import FamilyFinances.Infrastructure.Configurations.DependencyInjectionConfiguration;
import FamilyFinances.Main;
import FamilyFinances.Views.Families.FamiliesWindow;
import FamilyFinances.Views.Members.MemberWindow;
import FamilyFinances.Views.Roles.RolesWindow;
import FamilyFinances.Views.Users.LoginUserWindow;
import FamilyFinances.Views.Users.UsersWindow;

/**
 *
 * @author johnarrieta
 */
public class MainWindow extends javax.swing.JFrame {

    private final DependencyContainer dependencyContainer;

    /**
     * Creates new form MainWindow
     *
     * @param container
     */
    public MainWindow(DependencyContainer container) {
        initComponents();
        dependencyContainer = container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuRoles = new javax.swing.JMenu();
        itemAgregarRoles = new javax.swing.JMenuItem();
        itemConsultarRoles = new javax.swing.JMenuItem();
        itemEditarRoles = new javax.swing.JMenuItem();
        itemEliminarRoles = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        subMenuRoles = new javax.swing.JMenu();
        itemListarTodosLosRoles = new javax.swing.JMenuItem();
        itemListarRolesPorNombre = new javax.swing.JMenuItem();
        itemListarRolesPorDescripcion = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemLogout = new javax.swing.JMenuItem();
        itemAddUser = new javax.swing.JMenuItem();
        itemFindUser = new javax.swing.JMenuItem();
        itemEditUser = new javax.swing.JMenuItem();
        itemDeleteUser = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemSubmenuReportUser = new javax.swing.JMenu();
        itemGetAllUsers = new javax.swing.JMenuItem();
        itemGetByNameUsers = new javax.swing.JMenuItem();
        itemGetByRolUsers = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        itemAddMember = new javax.swing.JMenuItem();
        itemFindMember = new javax.swing.JMenuItem();
        itemEditMember = new javax.swing.JMenuItem();
        itemDeleteMember = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        itemSubmenuReportMembers = new javax.swing.JMenu();
        itemGetAllMembers = new javax.swing.JMenuItem();
        itemGetByNameMembers = new javax.swing.JMenuItem();
        itemGetByRolMembers = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemCreateFamily = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenuItem52 = new javax.swing.JMenuItem();
        jMenuItem53 = new javax.swing.JMenuItem();
        jMenuItem54 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem55 = new javax.swing.JMenuItem();
        jMenuItem56 = new javax.swing.JMenuItem();
        jMenuItem57 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menuRoles.setText("Roles");
        menuRoles.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        itemAgregarRoles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemAgregarRoles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/add24px.png"))); // NOI18N
        itemAgregarRoles.setText("Agregar...");
        itemAgregarRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarRolesActionPerformed(evt);
            }
        });
        menuRoles.add(itemAgregarRoles);

        itemConsultarRoles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemConsultarRoles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/search24px.png"))); // NOI18N
        itemConsultarRoles.setText("Consultar...");
        itemConsultarRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarRolesActionPerformed(evt);
            }
        });
        menuRoles.add(itemConsultarRoles);

        itemEditarRoles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemEditarRoles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/edit24px.png"))); // NOI18N
        itemEditarRoles.setText("Editar...");
        itemEditarRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarRolesActionPerformed(evt);
            }
        });
        menuRoles.add(itemEditarRoles);

        itemEliminarRoles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemEliminarRoles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/delete24px.png"))); // NOI18N
        itemEliminarRoles.setText("Eliminar...");
        itemEliminarRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarRolesActionPerformed(evt);
            }
        });
        menuRoles.add(itemEliminarRoles);
        menuRoles.add(jSeparator9);

        subMenuRoles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/list24px.png"))); // NOI18N
        subMenuRoles.setText("Reportes");
        subMenuRoles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemListarTodosLosRoles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemListarTodosLosRoles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/list24px.png"))); // NOI18N
        itemListarTodosLosRoles.setText("Listar todo...");
        subMenuRoles.add(itemListarTodosLosRoles);

        itemListarRolesPorNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemListarRolesPorNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/list24px.png"))); // NOI18N
        itemListarRolesPorNombre.setText("Listar por nombre...");
        subMenuRoles.add(itemListarRolesPorNombre);

        itemListarRolesPorDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemListarRolesPorDescripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/list24px.png"))); // NOI18N
        itemListarRolesPorDescripcion.setText("Listar por descripción...");
        subMenuRoles.add(itemListarRolesPorDescripcion);

        menuRoles.add(subMenuRoles);

        jMenuBar1.add(menuRoles);

        jMenu1.setMnemonic('U');
        jMenu1.setText("Usuarios");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu1.setName("menuUsuarios"); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        itemLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/logout24px.png"))); // NOI18N
        itemLogout.setMnemonic('C');
        itemLogout.setText("Cerrar sesion");
        itemLogout.setToolTipText("Te permite cerrar la sesion de login");
        itemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(itemLogout);

        itemAddUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/add24px.png"))); // NOI18N
        itemAddUser.setText("Agregar...");
        itemAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddUserActionPerformed(evt);
            }
        });
        jMenu1.add(itemAddUser);

        itemFindUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemFindUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/search24px.png"))); // NOI18N
        itemFindUser.setText("Consultar...");
        jMenu1.add(itemFindUser);

        itemEditUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemEditUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/edit24px.png"))); // NOI18N
        itemEditUser.setText("Editar...");
        jMenu1.add(itemEditUser);

        itemDeleteUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemDeleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/delete24px.png"))); // NOI18N
        itemDeleteUser.setText("Eliminar...");
        jMenu1.add(itemDeleteUser);
        jMenu1.add(jSeparator1);

        itemSubmenuReportUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/Users24px.png"))); // NOI18N
        itemSubmenuReportUser.setText("Reportes");
        itemSubmenuReportUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemGetAllUsers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGetAllUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/Users24px.png"))); // NOI18N
        itemGetAllUsers.setText("Listar todo...");
        itemSubmenuReportUser.add(itemGetAllUsers);

        itemGetByNameUsers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGetByNameUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/Users24px.png"))); // NOI18N
        itemGetByNameUsers.setText("Listar por nombre...");
        itemSubmenuReportUser.add(itemGetByNameUsers);

        itemGetByRolUsers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGetByRolUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/Users24px.png"))); // NOI18N
        itemGetByRolUsers.setText("Listar por Rol...");
        itemGetByRolUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGetByRolUsersActionPerformed(evt);
            }
        });
        itemSubmenuReportUser.add(itemGetByRolUsers);

        jMenu1.add(itemSubmenuReportUser);

        jMenuBar1.add(jMenu1);

        jMenu9.setMnemonic('U');
        jMenu9.setText("Miembros");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu9.setName("menuUsuarios"); // NOI18N
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });

        itemAddMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemAddMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/add24px.png"))); // NOI18N
        itemAddMember.setText("Agregar...");
        itemAddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddMemberActionPerformed(evt);
            }
        });
        jMenu9.add(itemAddMember);

        itemFindMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemFindMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/search24px.png"))); // NOI18N
        itemFindMember.setText("Consultar...");
        jMenu9.add(itemFindMember);

        itemEditMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemEditMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/edit24px.png"))); // NOI18N
        itemEditMember.setText("Editar...");
        jMenu9.add(itemEditMember);

        itemDeleteMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemDeleteMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/delete24px.png"))); // NOI18N
        itemDeleteMember.setText("Eliminar...");
        jMenu9.add(itemDeleteMember);
        jMenu9.add(jSeparator10);

        itemSubmenuReportMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/Users24px.png"))); // NOI18N
        itemSubmenuReportMembers.setText("Reportes");
        itemSubmenuReportMembers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemGetAllMembers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGetAllMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/Users24px.png"))); // NOI18N
        itemGetAllMembers.setText("Listar todo...");
        itemSubmenuReportMembers.add(itemGetAllMembers);

        itemGetByNameMembers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGetByNameMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/Users24px.png"))); // NOI18N
        itemGetByNameMembers.setText("Listar por nombre...");
        itemSubmenuReportMembers.add(itemGetByNameMembers);

        itemGetByRolMembers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGetByRolMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyFinances/Views/Icons/Users24px.png"))); // NOI18N
        itemGetByRolMembers.setText("Listar por Rol en la Familia...");
        itemGetByRolMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGetByRolMembersActionPerformed(evt);
            }
        });
        itemSubmenuReportMembers.add(itemGetByRolMembers);

        jMenu9.add(itemSubmenuReportMembers);

        jMenuBar1.add(jMenu9);

        jMenu2.setText("Familias");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        itemCreateFamily.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemCreateFamily.setText("Agregar...");
        itemCreateFamily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreateFamilyActionPerformed(evt);
            }
        });
        jMenu2.add(itemCreateFamily);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem10.setText("Consultar...");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem11.setText("Editar...");
        jMenu2.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem12.setText("Eliminar...");
        jMenu2.add(jMenuItem12);
        jMenu2.add(jSeparator2);

        jMenu12.setText("Reportes");
        jMenu12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem13.setText("Listar todo...");
        jMenu12.add(jMenuItem13);

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem14.setText("Listar por nombre...");
        jMenu12.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem15.setText("Listar por Rol...");
        jMenu12.add(jMenuItem15);

        jMenu2.add(jMenu12);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ingresos");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem16.setText("Agregar...");
        jMenu3.add(jMenuItem16);

        jMenuItem17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem17.setText("Consultar...");
        jMenu3.add(jMenuItem17);

        jMenuItem18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem18.setText("Editar...");
        jMenu3.add(jMenuItem18);

        jMenuItem19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem19.setText("Eliminar...");
        jMenu3.add(jMenuItem19);
        jMenu3.add(jSeparator3);

        jMenu13.setText("Reportes");
        jMenu13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem20.setText("Listar todo...");
        jMenu13.add(jMenuItem20);

        jMenuItem21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem21.setText("Listar por nombre...");
        jMenu13.add(jMenuItem21);

        jMenuItem22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem22.setText("Listar por Rol...");
        jMenu13.add(jMenuItem22);

        jMenu3.add(jMenu13);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Gastos");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuItem23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem23.setText("Agregar...");
        jMenu4.add(jMenuItem23);

        jMenuItem24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem24.setText("Consultar...");
        jMenu4.add(jMenuItem24);

        jMenuItem25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem25.setText("Editar...");
        jMenu4.add(jMenuItem25);

        jMenuItem26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem26.setText("Eliminar...");
        jMenu4.add(jMenuItem26);
        jMenu4.add(jSeparator4);

        jMenu14.setText("Reportes");
        jMenu14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem27.setText("Listar todo...");
        jMenu14.add(jMenuItem27);

        jMenuItem28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem28.setText("Listar por nombre...");
        jMenu14.add(jMenuItem28);

        jMenuItem29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem29.setText("Listar por Rol...");
        jMenu14.add(jMenuItem29);

        jMenu4.add(jMenu14);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Fuentes");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuItem30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem30.setText("Agregar...");
        jMenu5.add(jMenuItem30);

        jMenuItem31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem31.setText("Consultar...");
        jMenu5.add(jMenuItem31);

        jMenuItem32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem32.setText("Editar...");
        jMenu5.add(jMenuItem32);

        jMenuItem33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem33.setText("Eliminar...");
        jMenu5.add(jMenuItem33);
        jMenu5.add(jSeparator5);

        jMenu15.setText("Reportes");
        jMenu15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem34.setText("Listar todo...");
        jMenu15.add(jMenuItem34);

        jMenuItem35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem35.setText("Listar por nombre...");
        jMenu15.add(jMenuItem35);

        jMenuItem36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem36.setText("Listar por Rol...");
        jMenu15.add(jMenuItem36);

        jMenu5.add(jMenu15);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Categorias");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuItem37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem37.setText("Agregar...");
        jMenu6.add(jMenuItem37);

        jMenuItem38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem38.setText("Consultar...");
        jMenu6.add(jMenuItem38);

        jMenuItem39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem39.setText("Editar...");
        jMenu6.add(jMenuItem39);

        jMenuItem40.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem40.setText("Eliminar...");
        jMenu6.add(jMenuItem40);
        jMenu6.add(jSeparator6);

        jMenu16.setText("Reportes");
        jMenu16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem41.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem41.setText("Listar todo...");
        jMenu16.add(jMenuItem41);

        jMenuItem42.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem42.setText("Listar por nombre...");
        jMenu16.add(jMenuItem42);

        jMenuItem43.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem43.setText("Listar por Rol...");
        jMenu16.add(jMenuItem43);

        jMenu6.add(jMenu16);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Ahorros");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuItem44.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem44.setText("Agregar...");
        jMenu7.add(jMenuItem44);

        jMenuItem45.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem45.setText("Consultar...");
        jMenu7.add(jMenuItem45);

        jMenuItem46.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem46.setText("Editar...");
        jMenu7.add(jMenuItem46);

        jMenuItem47.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem47.setText("Eliminar...");
        jMenu7.add(jMenuItem47);
        jMenu7.add(jSeparator7);

        jMenu17.setText("Reportes");
        jMenu17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem48.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem48.setText("Listar todo...");
        jMenu17.add(jMenuItem48);

        jMenuItem49.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem49.setText("Listar por nombre...");
        jMenu17.add(jMenuItem49);

        jMenuItem50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem50.setText("Listar por Rol...");
        jMenu17.add(jMenuItem50);

        jMenu7.add(jMenu17);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Contribuciones");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuItem51.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem51.setText("Agregar...");
        jMenu8.add(jMenuItem51);

        jMenuItem52.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem52.setText("Consultar...");
        jMenu8.add(jMenuItem52);

        jMenuItem53.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem53.setText("Editar...");
        jMenu8.add(jMenuItem53);

        jMenuItem54.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem54.setText("Eliminar...");
        jMenu8.add(jMenuItem54);
        jMenu8.add(jSeparator8);

        jMenu18.setText("Reportes");
        jMenu18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem55.setText("Listar todo...");
        jMenu18.add(jMenuItem55);

        jMenuItem56.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem56.setText("Listar por nombre...");
        jMenu18.add(jMenuItem56);

        jMenuItem57.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem57.setText("Listar por Rol...");
        jMenu18.add(jMenuItem57);

        jMenu8.add(jMenu18);

        jMenuBar1.add(jMenu8);

        jMenu10.setText("Ayuda");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAgregarRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarRolesActionPerformed
        // TODO add your handling code here:
        RolesWindow window = new RolesWindow(this, true, dependencyContainer);
        window.enableButtons(false, false, false, false, true);
        window.setLocationRelativeTo(this);
        window.setVisible(true);

    }//GEN-LAST:event_itemAgregarRolesActionPerformed

    private void itemConsultarRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarRolesActionPerformed
        itemAgregarRolesActionPerformed(evt);
    }//GEN-LAST:event_itemConsultarRolesActionPerformed

    private void itemEditarRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarRolesActionPerformed
        // TODO add your handling code here:
        itemAgregarRolesActionPerformed(evt);
    }//GEN-LAST:event_itemEditarRolesActionPerformed

    private void itemEliminarRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarRolesActionPerformed
        // TODO add your handling code here:
        itemAgregarRolesActionPerformed(evt);
    }//GEN-LAST:event_itemEliminarRolesActionPerformed

    private void itemGetByRolUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGetByRolUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemGetByRolUsersActionPerformed

    private void itemAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddUserActionPerformed
        // TODO add your handling code here:
        var window = new UsersWindow(this, true, dependencyContainer);
        window.enableButtons(true, true, false, false, true);
        window.setLocationRelativeTo(this);
        window.setVisible(true);
    }//GEN-LAST:event_itemAddUserActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void itemCreateFamilyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreateFamilyActionPerformed
        var window = new FamiliesWindow(this, true, dependencyContainer);
        window.enableButtons(true, true, false, false, true);
        window.setLocationRelativeTo(this);
        window.setVisible(true);
    }//GEN-LAST:event_itemCreateFamilyActionPerformed

    private void itemAddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddMemberActionPerformed
        // TODO add your handling code here:
        var window = new MemberWindow(this, true, dependencyContainer);
        window.setLocationRelativeTo(this);
        window.setVisible(true);
    }//GEN-LAST:event_itemAddMemberActionPerformed

    private void itemGetByRolMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGetByRolMembersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemGetByRolMembersActionPerformed

    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu9ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        var window = new LoginUserWindow(this, true, dependencyContainer);
        window.setLocationRelativeTo(this);
        window.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void itemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLogoutActionPerformed
        // TODO add your handling code here:
        Main.currentUser = null;
        formWindowOpened(null);
    }//GEN-LAST:event_itemLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                var container = DependencyContainer.getInstance();
                DependencyInjectionConfiguration.registerDependencies(container);
                new MainWindow(container).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAddMember;
    private javax.swing.JMenuItem itemAddUser;
    private javax.swing.JMenuItem itemAgregarRoles;
    private javax.swing.JMenuItem itemConsultarRoles;
    private javax.swing.JMenuItem itemCreateFamily;
    private javax.swing.JMenuItem itemDeleteMember;
    private javax.swing.JMenuItem itemDeleteUser;
    private javax.swing.JMenuItem itemEditMember;
    private javax.swing.JMenuItem itemEditUser;
    private javax.swing.JMenuItem itemEditarRoles;
    private javax.swing.JMenuItem itemEliminarRoles;
    private javax.swing.JMenuItem itemFindMember;
    private javax.swing.JMenuItem itemFindUser;
    private javax.swing.JMenuItem itemGetAllMembers;
    private javax.swing.JMenuItem itemGetAllUsers;
    private javax.swing.JMenuItem itemGetByNameMembers;
    private javax.swing.JMenuItem itemGetByNameUsers;
    private javax.swing.JMenuItem itemGetByRolMembers;
    private javax.swing.JMenuItem itemGetByRolUsers;
    private javax.swing.JMenuItem itemListarRolesPorDescripcion;
    private javax.swing.JMenuItem itemListarRolesPorNombre;
    private javax.swing.JMenuItem itemListarTodosLosRoles;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JMenu itemSubmenuReportMembers;
    private javax.swing.JMenu itemSubmenuReportUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem56;
    private javax.swing.JMenuItem jMenuItem57;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenu menuRoles;
    private javax.swing.JMenu subMenuRoles;
    // End of variables declaration//GEN-END:variables
}
